### ISSUE TITLE
Specify self-signed certificate instead of keystore location

### ISSUE THREAD

**Issue by stevenroose** [lgallard/qBittorrent-Controller#103]
I'm trying to setup qBittorrent-Controller with a self-signed certificate, but the app asks for the location of the keystore that it's in. I have no idea if I can even go to that location using my explorer app, let alone I would know where to look for. I have the certificate file taken from my server, so it would be a lot more useful if I could just point to the file directly.

**Comment by lgallard** [comment]
Due to Google is now more strict in the handling of SSL certificates in Android, they forced developers stop using insecure implementations for self-signed certificates. To accomplish this now you must generate a BouncyCastle Keystore (BKS) to use self-signed certificates with qBittorrent Controller.

You can check how to generate the certificate and its BKS file here https://github.com/lgallard/qBittorrent-Controller/wiki/Using-Self-Signed-Certificates
