### ISSUE TITLE
Notifications Quit Working

### ISSUE THREAD

**Issue by icarri718** [lgallard/qBittorrent-Controller#171]
Hi,

Everything was working perfect with the app for about 2 weeks, until 2 days ago all notifications stopped. Tried changing the options, checked my app permissions, and uninstalled and reinstalled. Still haven't been able to get it work. Anything else I can try? Running Android 8.0.0

ETA: Tried restarting phone and computer. Had 3 torrents running, didn't receive notification for the first one that finished, received notification for the second one, and then none for the third.

**Comment by rbtmarshall** [comment]
I had this same problem over the past few weeks and it appears to be fixed by resetting the username and password in the qbittorrent host on my computer and app

qbittorrent on the host computer, change username and password:
Tools>options>web UI    Authentication

Then update the server username and password settings in the app:
Menu>settings 

Hope this helps

**Comment by lgallard** [comment]
This is fixed in the new upcoming 4.7.0 release

**Comment by lgallard** [comment]
qBController v4.7.0 fixes it!
