### ISSUE TITLE
APK missing from latest release

### ISSUE THREAD

**Issue by IzzySoft** [lgallard/qBittorrent-Controller#187]
Somehow, the v4.7.3 release has no APK file attached – guess it was simply forgotten. Could you please add it? Thanks!

**Comment by lgallard** [comment]
That was odd, I uploaded but somehow it didn't work. Now it's available!

**Comment by IzzySoft** [comment]
[Confirmed](https://apt.izzysoft.de/fdroid/index/apk/com.lgallardo.qbittorrentclient) by my updater, thanks! :smiley:

**Comment by lgallard** [comment]
You are welcome. I have to automate this. Maybe using GitHub Actions!

**Comment by lgallard** [comment]
By the way, nice APK repository.

**Comment by IzzySoft** [comment]
Thanks! Serves as a mix of "staging" (for apps not-yet-ready) and "non-free" (for apps never ready) for the official repo. Often it's just "small things" hindering an app to get listed (like in your case, GMS, which is proprietary). If it's not too heavy (for GMS, folks using microG might not be too offended), and the APK is available (plus some more rules), I **pick** it. If it's "more trackers than main features", I **kick** it :rofl:

Should you decide to offer a FOSS flavor, I of course gladly help getting it into the [main repo](https://f-droid.org/) if you wish. As above term "staging" indicates, such moves happen regularly (about 150 times in the past already).

**Comment by lgallard** [comment]
I know qBController was in F-Droid repos a time ago. The thing is I'm using GMS (rignt now I don't remember why, I guess due to ads) and I don't know if the project applies as pure FOSS. 

My idea is to have a free version and a paid version (the Pro). Both with the same functionalities for handling torrents but having a paid version without ads and a "better" UI. Code for both versions are public here at this repo, and anyone can even build the pro version but if you don't want bother on that you can paid the pro version and have it delivered from  Google Play.

Another idea of having a free version was to have collaborators, but there have been too little interested.

**Comment by IzzySoft** [comment]
> I know qBController was in F-Droid repos a time ago. The thing is I'm using GMS (rignt now I don't remember why, I guess due to ads) and I don't know if the project applies as pure FOSS.

No, due to GMS it does not apply as „pure FOSS“ – which is why it's in my repo instead of the official one (and yes, as you're using *Google Ads* according to my library scanner, that's the most likely reason for GMS here).

> Code for both versions are public here at this repo, and anyone can even build the pro version

My idea was to have a FOSS build flavor which F-Droid could pick up. Whether that would be the paid or the free version, we'd totally leave up to you (disclosure: I'm one of the F-Droid maintainers): several apps ship their full versions, which are paid at Play Store, for free via F-Droid (OsmAnd probably being the most prominent). Some do it explicitly to steer users out of Google's walled garden towards a privacy friendly environment (e.g. FediLab). Others have their free versions at both places (on F-Droid minus proprietary elements, trackers, ads etc), and the paid on Play. So there's plenty of choice :smile:

> Another idea of having a free version was to have collaborators, but there have been too little interested.

Unfortunately true, not only for your project :cry:

**Comment by lgallard** [comment]
Right now I don't have a quick / easy way of removing ads libraries for the free version (and the pro one as well, because it's the same code at the end). I have to come up with an idea for building the free APK here at Github (using Actions, for instance) and maybe this can generate an ads frees version for both versions, Free & Pro.

Sometimes its not easy to satisfies all at the same time, devs and users :)

**Comment by IzzySoft** [comment]
Yeah, I know. That's why my repo so often serves as intermediate. Happy to do so here again. So: whenever you're ready, just let me know. And maybe a build flavor is the way to go (I'm no Android dev, so I can only speak from what I've read, not from experience)…
