### ISSUE TITLE
Can not connect to host

### ISSUE THREAD

**Issue by RikkaBlue** [lgallard/qBittorrent-Controller#205]
I use [frp](https://github.com/fatedier/frp) to access to the host.
I can visit the webui on browser, which uses nginx to get https access.
But I can not connect to the host with the app.

There is no error. It is just loading infinitely. 
I fill in the host with my domain, also the port has been changed to 443, and I also check the https option.

The app version is 4.7.5 on android pie.
qbitTorrent-nox version is  v4.1.9.1.

**Comment by lgallard** [comment]
Hi @RikkaBlue , if you have a subfolder set it on qBController. If not, then it my be related to [this issue](https://github.com/lgallard/qBittorrent-Controller/issues/178#issuecomment-565783867)

**Comment by lgallard** [comment]
Also check the qBittorent doicumentation for [reverse proxing for nginex ](https://github.com/qbittorrent/qBittorrent/wiki/NGINX-Reverse-Proxy-for-Web-UI)  and adapt it to your proxy. In particular, set te referer and origin headers as blank.

**Comment by L11R** [comment]
Similar setup (but I don't use `frp`, just `nginx`), same issue, same qBittorrent-nox version, qBittorrent Controller Pro 4.7.8.

It worked perfectly until few updates, but now just loads infinitely. I guess I have the same issue as @Rouzax has.

**Comment by sooonmitch** [comment]
Same issue, not using nginx or anything in-between. Was working a couple updates ago but randomly stopped.

Version: 4.8.4
Phone: Pixel XL

I uninstalled and reinstalled the app. Also wiped and readded the server info. Still the same issue. No errors, just a continuous loading icon. I can access the server's webui via the same device under the same conditions. Just seems like the app is trying to timeout but never does.

**Comment by sooonmitch** [comment]
@lgallard 
Perhaps it might be worth while to add a logger to the app? That way, any errors or warnings are logged and the user can either report them here or possibly even debug it on there own.

**Comment by lgallard** [comment]
@sooonmitch that was the idea of the report generator, but maybe there's room for improvement here.

**Comment by CircleG0d** [comment]
I am also having the issue with the Android App (4.8.4) "qBittorrent Controller Pro" using a Pixel 3a running Android Version 10. 

When I try and connect it just spins. I have re-verified the information and re-installed the application. I verified I can access it via chrome on the phone and another device. 

I do not use proxy, HTTPS or anything fancy, just local IP and standard auth. I do not use it remotely.

Please help, I miss this app :D

**Comment by lgallard** [comment]
@CircleG0d check release 4.8.7

**Comment by simplethemind** [comment]
From what I can see in the code, issue is related to the following code which is repeated throughout mainActivity
```
         String url = "";

         // if server is publish in a subfolder, fix url
         if (subfolder != null && !subfolder.equals("")) {
             url = subfolder + "/" + url;
         }

         url = protocol + "://" + hostname + ":" + port + url;
```
If you're using nginx, you are probably using a reverse proxy of the sort:
`https://mysite.com/qbt` or `https:/qbt.mysite.com`
because nginx handles all the port forwarding for you.

However, this code adds the `":" + port` part for you, which will not work, even though port is set to "". So you get something like `https:/mysite.com:/qbt/` which is wrong. You can try 443 for the port, but nginx will not understand it either way.

This should add a check to see if the port field exists and write the ":" part only if there's a port number following it.

Another suggestion I have is to check for leading slashes in the subfolder name and, if missing, add it before the url part.

Another suggestion would be to encapsulate this code in a separate method so that any further tweaks can be done in only one place, not in about 27 places (might have missed some of them).

@lgallard I can try to fork the project and make a pull request later today.

**Comment by lgallard** [comment]
@simplethemind nice catch. Thanks for the nginx insight!!

**Comment by pedroapero** [comment]
Same issue, I can't make it work, qbittorrent-nox 4.2.5 and qbittorrent client pro 3.9.0 (I posted first in #90).
