### ISSUE TITLE
qBittorrent: "Sequential download" and "First and last pieces" toggles don't work

### ISSUE THREAD

**Issue by olavinto** [lgallard/qBittorrent-Controller#246]
"Sequential download" and "First and last pieces" toggles don't work. They work fine on the server but remotely, through the app they do not do anything except show a notification that the option is toggled when in fact it is not. The checkboxes in the torrent information remain inactive.

**Comment by lgallard** [comment]
@olavinto thanks for reporting the issue. I will include a fix in a future release!

**Comment by Alexey71** [comment]
Hi. Soon new release?

**Comment by hrap1919** [comment]
It seems the toggles work correctly. They successfully send the webAPI-command to the server.  The problem is in the checkboxes. Their states is always off by the current code. I have added some code and (at least) the checkbox states now change after re-entering into the torrent details activity. See the modified apk and  source diffs here: https://4pda.ru/forum/index.php?showtopic=610036&view=findpost&p=102317934

**Comment by olavinto** [comment]
> 
> 
> It seems the toggles in menu work correctly. They successfully send the webAPI-commands to the server. The problem is in the checkboxes. Their states are always off by the current code. I have added some code and (at least) the checkbox states now change after re-entering into the torrent details activity. See the modified apk and source diffs here: https://4pda.ru/forum/index.php?showtopic=610036&view=findpost&p=102317934
Yeah, I confirm that they toggle the options but the change is just not shown in the app.
