### ISSUE TITLE
Is the app support qBittorrent-nox?

### ISSUE THREAD

**Issue by akaneko252** [lgallard/qBittorrent-Controller#90]
Hi.
When I finish the setting in app,it's nothing change after I press the refresh button,it show me no error notice.
I run qBittorrent-nox v3.1.8 in a ubuntu 14.04 VPS.Web UI has been enabled.The username and password in app setting is just the same of Web UI,the connection port in advanced is the same of [tools/options/connection/listening port/Port used for incoming connections].Ofcourse the port is allowed in firewall.
Is here something wrong about the setting?Thank you!

**Comment by lgallard** [comment]
It works with qBittorrent-nox as far you enable the WebUI as you did.

According to the description it might be related to #89. If it's the first time you installed it. Close it, even from the app list, then launch it and double check your username and password in settings.

Please keep me posted!

**Comment by akaneko252** [comment]
Thanks for your respond.

It's no effect with following your advice. If I make a wrong ip or port, it will notice " The host or IP address cannot be reached ". But now it's no results and error message. Of course I check the username and password. And I can connect webui in the same android by browser.

My network has some limit to foreign website, So I have to make VPS to bulid VPN. I can't direct connect webui, unless through the VPN on the same VPS. But all apps in my android 4.4.2 can go through the VPN. Is the problem of VPS?

**Comment by lgallard** [comment]
There is an issue when adding your account the first time, if by mistake you set your account wrongly (username or password), the app tries to connect several times without showing any error or message. Because these authentication failures the qBittorrent server bans your device's IP address. To check if you have been banned, try to reach your qBittorrent WebUI from your Android device browser.

To remove the ban and get connected, the workaround is the following:

1. Check your account settings (specially the password that is hidden)
2. Close the Android app completely. Even remove it from the recent app list.
3. Restart the qBittorrent WebUI interface (by disable/enabling or by closing/opening qBittorrent) to remove the ban. 
4. Launch the app one more time. It

On the other hand, I've connected it successfully through a VPN. Check if the VPN allows the qBittorrent server port (default 8080).

Keep me posted!

**Comment by akaneko252** [comment]
Hi.

I think the problem is just the ban. I try in android emulator, it does work! When following your step in android phone, I have tried to clean all the data, reinstall the app, reboot android phone, restart qbittorrent-nox service, even reboot my VPS, but all the same result. 

There's something strange about it. Although the app always warning " The host or IP address cannot be reached ", one time I keep refreshing over 10 times, suddenly it can get the result! But just the result so I can't edit anything, then the result gone with the next refresh. I can't find how to disable the webui in qbittorrent-nox, it's the last step haven't tried.

**Comment by lgallard** [comment]
Also try increasing the connection and data timeout in settings!

**Comment by lgallard** [comment]
Hi,
I just updated a new version. I hope it fixed the issue.

Please keep me posted!

Regards,

**Comment by akaneko252** [comment]
Thank you very much.

For unlock the ban, and sometimes I need to DL part of the whole torrent, I change qBittorrent-nox for qBittorrent to solve the problem. But the qBittorrent also have many bugs OTL.

In last version the connection and data timeout settings both can't be saved.

Thank you again!

**Comment by pedroapero** [comment]
I can't make it work either. I've updated to qbittorrent-nox 4.2.5. I'm using qbittorrent client pro 3.9.0 from f-droid.

This is what I've tried so far:
- disabling authentication in qbittorrent-nox and removing username and password in QC
- enabling authentication and trying with a correct password
- enabling authentication and trying with an incorrect password => no failed login attempt is loged in qbittorrent-nox!
- changing qBittorrent version (2.x/3.1.x/3.2.x) in QC
- increasing connection and data timeout as suggested by @lgallard
- restarting qbittorrent-nox and QC

Unfortunately, each time I get the equivalent of «network connection failed» immediately.

I can confirm I'm able to use the webUI from my web browser (directly on the local network) using the configured IP and port (HTTP).

Can you give me a hint?
